@startuml
'https://plantuml.com/sequence-diagram

autoactivate on
autonumber



participant "u1:User" as Userl1
participant "u2:User" as Userl2
participant "a1:Auth" as Autha1
participant "a2:Auth" as Autha2



 -> Userl1 : Htpp Post(/api/users)


Userl1 -> Userl1 : save Usersu1
Userl1 --> Userl1 : saved Usersu1

Userl1 -> Userl2: Htpp Post (/internal/users)
Userl2 --> Userl1: 200 OK

Userl1 -> Autha1: Htpp Post (/auth/register)
Autha1 -> Autha2: Htpp Post (/internal/auth)
Autha2 --> Autha1: 200 OK
Autha1 --> Userl1: 200 OK

 <-- Userl1 : 201



@enduml