@startuml
'https://plantuml.com/sequence-diagram

autoactivate on
autonumber

title I want to update an author’s data

participant "a1:AuthorBE" as Userl1
participant "a1:AuthorDB" as Userl2
participant "a2:AuthorBE" as Userl3
participant "a2:AuthorDB" as Userl4



 -> Userl1 : Htpp Patch(/api/author)


Userl1 -> Userl2 : save Authorl1
Userl2 -> Userl2 : saved Authorl1
Userl2 --> Userl2 : saved Authorl1
Userl2 --> Userl1 : saved Authorl1





Userl1 -> Userl3: Htpp Post (/internal/author)
Userl3 -> Userl4 : save Authorl1
Userl4 -> Userl4 : saved Authorl1
Userl4 --> Userl4 : saved Authorl1
Userl4 --> Userl3: 200 OK
Userl3 --> Userl1: 200 OK


 <-- Userl1 : 200



@enduml