@startuml
'https://plantuml.com/sequence-diagram

autoactivate on
autonumber



participant "l1:LendingsBE" as Lendingsl1
participant "l1:LendingsDB" as Lendingsl2
participant "l2:LendingsBE" as Lendingsl3
participant "l2:LendingsDB" as Lendingsl4
participant "u1:UserBE" as Useru1
participant "u1:UserDB" as Useru2
participant "b1:BookBE" as Bookb1
participant "b1:BookDB" as Bookb2




 -> Lendingsl1 : Htpp Post(/api/lendigs)
Lendingsl1 -> Useru1: GET /users/{ReaderNumber} (Verify user existence)
Useru1 -> Useru2: findByReaderNumber
Useru2 --> Useru1: OK
Useru1 --> Lendingsl1: 200 OK (User details)
Lendingsl1 -> Bookb1: GET /books/{Isbn} (Verify book existence)
Bookb1 -> Bookb2: findByIsbn
Bookb2 --> Bookb1: OK
Bookb1 --> Lendingsl1: 200 OK (Book details)

Lendingsl1 -> Lendingsl2 : save Lendingsl1
Lendingsl2 -> Lendingsl2 : save Lendingsl1
Lendingsl2 --> Lendingsl2 : saved Lendingsl1
Lendingsl2 --> Lendingsl1 : saved Lendingsl1


Lendingsl1 -> Lendingsl3: Htpp Post (/internal/lendigs)
Lendingsl3 -> Lendingsl4 : save Lendingsl1
Lendingsl4 -> Lendingsl4 : save Lendingsl1
Lendingsl4 --> Lendingsl4 : saved Lendingsl1
Lendingsl4 --> Lendingsl3 : saved Lendingsl1
Lendingsl3 --> Lendingsl1: 200 OK

 <-- Lendingsl1 : 201



@enduml